#!/bin/bash
#
# Author: Max Idermark
# GitHub Repo: https://github.com/Accelerox/wireguard-namespace
#
# This script sets up a bridge interface (br0) on your system.
#
# Usage: ./wg-netns-install

# Check if the script is run with sudo
if [[ $EUID -ne 0 ]]; then
    echo "This script must be run with sudo"
    exit 1
fi

# Create bridge br0
ip link add name br0 type bridge
ip link set dev br0 up
