#!/bin/bash
#
# Author: Max Idermark
# GitHub Repo: https://github.com/Accelerox/wireguard-namespace
#
# This script executes the given command in the specified namespace.
# Make sure the command is in quotes ""
#
# Usage: ./wg-netns-execute <identifier> "<command>"

# Check if the script is run with sudo
if [[ $EUID -ne 0 ]]; then
    echo "This script must be run with sudo"
    exit 1
fi

if [[ $# -ne 2 ]]; then
    echo "Usage: $0 <identifier> \"<command>\""
    exit 1
fi

identifier=$1
command=$2

# Check if the namespace exists
if ! ip netns list | grep -q -w "${identifier}"; then
    echo "Namespace '${identifier}' not found"
    exit 1
fi

# Execute the command in the specified namespace
ip netns exec ${identifier} bash -c "${command}"
