#!/bin/bash
#
# Author: Max Idermark                                                                                                                    
# GitHub Repo: https://github.com/Accelerox/wireguard-namespace
#
# This script removes all WireGuard VPN instances, their corresponding namespaces, and the bridge.
#
# Usage: ./wg-netns-remove

# Check if the script is run with sudo
if [[ $EUID -ne 0 ]]; then
    echo "This script must be run with sudo"
    exit 1
fi

# Get a list of all the VPN instances' namespaces
namespaces=$(ip netns list | grep -oP '^\w+(?=\s)')

# Remove all the VPN instances' namespaces and their corresponding folders
for ns in $namespaces; do
    # Remove the namespace
    ip netns del ${ns}

    # Remove the bridge connection to the namespace
    ip link del veth-nsbr-${ns}

    # Remove the virtual Ethernet (veth) interfaces
    ip link del veth-init-${ns}

    # Remove the WireGuard interface from the default/init namespace (auto done)
    #ip link del wg0-${ns}

    # Remove the namespace folder
    rm -rf /etc/netns/${ns}
done

# Remove the bridge br0
nmcli connection delete bridge-br0
